export const products = [
    {
        id: 1,
        title: "2022 Apple MacBook Air Laptop ",
        description: "Liquid Retina Display",
        price: "149900",
        img: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg",
        quantity: 1,
    },

    {
        id: 2,
        title: "Adidas Outdoor Men's Terrex Two GTX",
        description: "flat heeled",
        price: "20764",
        img: "https://m.media-amazon.com/images/I/61jkTjmZ6NL._UL1080_.jpg",
        quantity: 1,
    },
    {
        id: 3,
        title: "Strauss Bronx Skateboard",
        description: "Multiple Design",
        price: "1173",
        img: "https://m.media-amazon.com/images/I/81pbtbAeulL._SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 4,
        title: "Iphone 12",
        description: "violet colour",
        price: "90500",
        img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
        quantity: 1,
    },

    {
        id: 5,
        title: "Redmi A1",
        description: "affordable",
        price: "6299",
        img: "https://m.media-amazon.com/images/I/81UmTnrBDSL._SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 6,
        title: "Redmi Note 11",
        description: "blue in color",
        price: "11999",
        img: "https://m.media-amazon.com/images/I/81zLNgcvlaL._SL1500_.jpg",
        quantity: 1
    },
    {
        id: 7,
        title: "Samsung S21",
        description: "black in color",
        price: "25000",
        img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        quantity: 1,
    },
    {
        id: 8,
        title: "Realme narzo 50i ",
        description: "mint green in color",
        price: "6749",
        img: "https://m.media-amazon.com/images/I/81QqVNKWtML._SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 9,
        title: "OnePlus Nord CE 2 Lite 5G",
        description: "Blue in color",
        price: "18999",
        img: "https://m.media-amazon.com/images/I/71AvQd3VzqL._SL1500_.jpg",
        quantity: 1,
    },
    {
        id: 10,
        title: "Apple iPhone 13 Pro",
        description: "For the Elite",
        price: "109900",
        img: "https://m.media-amazon.com/images/I/61sDyXAepuL._SL1500_.jpg",
        quantity: 1,
    },
];